version: '3.4'

volumes:
  storage_volume:
    driver: local
    driver_opts:
      type: none
      device: /data/
      o: bind
services:
  seedlyserverapp:
    image: ${DOCKER_REGISTRY-}seedlyserverapp
    build:
      context: .
      dockerfile: SeedlyGUI/SeedlyServerApp/Dockerfile
    ports:
      - "90:80"
    links:
      - "seedlyserver:server"
  seedlyserver:
    image: ${DOCKER_REGISTRY-}seedlyserver
    build:
      context: .
      dockerfile: SeedlyServer/Dockerfile
    ports:
      - "50005:50005"
    volumes:
      - storage_volume:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

